# hparams_config.yaml

# Training dynamics
batch_size: 256
accumulation_steps: 2
epochs: 300
warmup_epochs: 5

# Model architecture
hidden_channels: 24
attn_embed_dim: 256
num_transformer_layers: 8

# Ap loss
min_perturb: 0.01
max_perturb: 0.05
ap_loss_weight: 1.0
perturbed_patch_sets: 3

# Regularization
stochastic_depth: 0.15
re_prob: 0.15
augment_magnitude: 5
mixup_alpha: 0.5
cutmix_alpha: 0.2
mixup_prob: 0.5
mixup_switch_prob: 0.5
label_smoothing: 0.05
weight_decay: 0.00015
