# hparams_config.yaml
batch_size: 256
epochs: 150
warmup_epochs: 10
stn_lr: 0.0001
transformer_lr: 0.0003
weight_decay: 0.000015
t_0: 40
t_mult: 2
eta_min: 0.00001
label_smoothing: 0.05
hidden_channels: 64
attn_embed_dim: 256
num_transformer_layers: 4
stn_dropout: 0.0
patch_dropout: 0.0
transformer_dropout: 0.4