# hparams_config.yaml
batch_size: 256
epochs: 300
lr_factor: 512
warmup_epochs: 5
weight_decay: 0.000015
eta_min: 0.0001
hidden_channels: 16
attn_embed_dim: 384
num_transformer_layers: 8
stochastic_depth: 0.15
label_smoothing: 0.05
re_prob: 0.15
augment_magnitude: 5
