# hparams_config.yaml
batch_size: 128
accumulation_steps: 2
epochs: 100
lr_factor: 256
warmup_epochs: 5
weight_decay: 0.00015
eta_min: 0.00015
hidden_channels: 16
attn_embed_dim: 256
num_transformer_layers: 6
stochastic_depth: 0.15
label_smoothing: 0.05
re_prob: 0.15
augment_magnitude: 5
